[project]
name = "ie-version2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.31.0",
    "langchain>=0.3.23",
    "langchain-groq>=0.3.7",
]
